# Permalinks
permalink:        pretty

# Setup
title:            'Creating The Commune'
tagline:          'A Journey'
description:      'A blog detailing the journey to create a commune on the West Coast.'
markdown:         kramdown
url:              http://creatingcommunes.com
baseurl:          /

author:
  name:           'Prateek'
  url:            prateek.app

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/creating-communes/website
