# Dependencies
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


# Permalinks
permalink:        pretty

# Setup
title:            'Creating The Commune'
tagline:          'A Journey'
description:      'A blog detailing the journey to create a commune on the West Coast.'
url:              http://creatingcommunes.com
baseurl:          /

author:
  name:           'Prateek'
  url:            prateek.app

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/creating-communes/website
